version: 2
updates:
  - package-ecosystem: "gradle" 
    directory: "/00-Login-Kt" 
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" 
    directory: "/00-Login" 
    schedule:
      interval: "daily"
